/* DEFINE('LAST_TS_DELETE') */
   SELECT 'stg_csv_transaction_merge' as key, to_char(MAX(_sys_updated_at),'yyyy-mm-dd hh24:mi:ss.us') as value
     FROM stg_csv_Transaction_merge
    WHERE _sys_is_deleted = true
   union all
   SELECT 'stg_csv_transactiondistribution_merge' as key, to_char(MAX(_sys_updated_at),'yyyy-mm-dd hh24:mi:ss.us') as value
     FROM stg_csv_TransactionDistribution_merge
    WHERE _sys_is_deleted = true
;